version: "3"

services:
  routeros:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8722:22"
      - "8723:23"
      - "8780:80"
      - "8728:8728"
      - "8729:8729"
